name: Testing

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  codeql:
    name: Security and Quality
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install -e .
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
        queries: security-and-quality
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Flake8
      uses: TrueBrain/actions-flake8@master
      with:
        path: tests wikitexthtml

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        black -l 120 --check tests wikitexthtml

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # Temporary till a new release is created
        python -m pip install git+https://github.com/5j9/wikitextparser.git
        python -m pip install -e .
    - name: Install pytest
      run: python -m pip install pytest
    - name: Run pytest
      run: pytest
